### A)Information Retreval system

### Loading 5 text files 

In [1]:
#loading into 5 documents
doc1=open('/content/365 bedtime stories by Mary Graham Bonner.txt','r')
doc2=open('/content/George Romney, by Rowley Cleeve.txt','r')
doc3=open('/content/Greuze by Harold Armitage.txt','r')
doc4=open('/content/History of the war in the Peninsula and in the south of France from the year.txt','r')
doc5=open('/content/Sir John Everett Millais by A. L. Baldry.txt','r')

### Preprocessing data

In [2]:
#converting into lowercase and removing stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopword=stopwords.words('english')
doc1_procd=[i.lower() for i in doc1.read().split() if i.lower() not in stopword]
doc2_procd=[i.lower() for i in doc2.read().split() if i.lower() not in stopword]
doc3_procd=[i.lower() for i in doc3.read().split() if i.lower() not in stopword]
doc4_procd=[i.lower() for i in doc4.read().split() if i.lower() not in stopword]
doc5_procd=[i.lower() for i in doc5.read().split() if i.lower() not in stopword]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [3]:
#Special characters,punctuations and numbers removal
import re
doc1_procd=[re.sub('[^A-Za-z]+','',i) for i in doc1_procd]
print(len(doc1_procd))
doc2_procd=[re.sub('[^A-Za-z]+','',i) for i in doc2_procd]
print(len(doc2_procd))
doc3_procd=[re.sub('[^A-Za-z]+','',i) for i in doc3_procd]
print(len(doc3_procd))
doc4_procd=[re.sub('[^A-Za-z]+','',i) for i in doc4_procd]
print(len(doc4_procd))
doc5_procd=[re.sub('[^A-Za-z]+','',i) for i in doc5_procd]
print(len(doc5_procd))

2715
1453
1862
519
2169


### Forming a dictionary by itretaing through unique words

In [4]:
#finding unique words
unq_wrds=set(doc1_procd).union(set(doc2_procd),set(doc3_procd),set(doc4_procd),set(doc5_procd))

In [5]:
len(unq_wrds)

3413

In [6]:
#forming doc_dict which indicates in which document particular word is present
from collections import defaultdict
doc_dict=defaultdict(list)
for i in unq_wrds:
  if i in set(doc1_procd):
    doc_dict[i].append(1)
  else:
    doc_dict[i].append(0)
  if i in set(doc2_procd):
    doc_dict[i].append(1)
  else:
    doc_dict[i].append(0)
  if i in set(doc3_procd):
   doc_dict[i].append(1)
  else:
    doc_dict[i].append(0)
  if i in set(doc4_procd):
    doc_dict[i].append(1)
  else:
    doc_dict[i].append(0)
  if i in set(doc5_procd):
   doc_dict[i].append(1)
  else:
    doc_dict[i].append(0)

In [7]:
doc_dict

defaultdict(list,
            {'': [1, 1, 1, 1, 1],
             'smaller': [0, 1, 0, 0, 0],
             'generals': [0, 0, 0, 1, 0],
             'unanimity': [0, 0, 0, 0, 1],
             'workmen': [0, 1, 0, 0, 0],
             'autumn': [1, 0, 0, 0, 1],
             'distracted': [0, 0, 1, 0, 0],
             'north': [1, 1, 0, 1, 0],
             'mend': [0, 0, 0, 0, 1],
             'transitional': [0, 0, 0, 0, 1],
             'accomplish': [0, 1, 0, 0, 0],
             'childs': [0, 0, 0, 0, 1],
             'palette': [0, 1, 0, 0, 0],
             'loved': [1, 1, 0, 0, 1],
             'watermelon': [1, 0, 0, 0, 0],
             'prevented': [0, 1, 0, 0, 0],
             'justified': [0, 1, 0, 0, 0],
             'relinquishes': [0, 0, 0, 1, 0],
             'elm': [1, 0, 0, 0, 0],
             'sweeps': [0, 0, 0, 1, 0],
             'keys': [1, 0, 0, 0, 0],
             'admiration': [1, 0, 0, 0, 0],
             'serious': [0, 1, 0, 0, 1],
             'checked': [0, 0, 0, 

In [8]:
#testing againist boolean query helper function 1
import numpy as np
from numpy import array
def excute_boolean(qry):
  qry=re.sub(r'\bor\b','+',qry)
  qry=re.sub(r'\band\b','*',qry)
  qry=re.sub(r'\bnot\b','np.array([1,1,1,1,1])-',qry)
  l=qry.split()
  for i in range (len(l)):
    if l[i].isalpha():
      if doc_dict[l[i]]:
        l[i]=repr(np.array(doc_dict[l[i]]))
      else:
        l[i]=repr(np.array([0,0,0,0,0]))
  evlqry=' '.join(l)
  return (evlqry)

In [9]:
#helper function 2
def redifine(l):
  for i in range (len(l)):
    if l[i]>1:
      l[i]=1
  return l

In [10]:
#helper function 3
def find_docs(doc_list):
  docs=['doc1','doc2','doc3','doc4','doc5']
  for i in list(zip(docs,doc_list)):
    if i[1]==1:
      print(i[0])

### Testing against different boolean queries

In [11]:
#input1
qry='brother and not device'
#print(excute_boolean(qry))
doc_list=eval(excute_boolean(qry))
doc_list=redifine(doc_list)
print(doc_list)

[0 1 0 0 0]


In [12]:
#returned document
find_docs(doc_list)

doc2


In [13]:
#input2
qry='sold and june or not fashionable'
doc_list=eval(excute_boolean(qry))
doc_list=redifine(doc_list)
doc_list

array([1, 1, 1, 1, 1])

In [14]:
find_docs(doc_list)

doc1
doc2
doc3
doc4
doc5


In [15]:
#input3
qry='sold and june'
doc_list=eval(excute_boolean(qry))
doc_list=redifine(doc_list)
print(doc_list)
find_docs(doc_list)

[0 1 0 0 1]
doc2
doc5


In [16]:
#input4
qry='azzz or dfg'
doc_list=eval(excute_boolean(qry))
doc_list=redifine(doc_list)
print(doc_list)
find_docs(doc_list)

[0 0 0 0 0]


###B) Inverted Index

In [17]:
#forming a dictionary of index
from collections import defaultdict
invrtd_index=defaultdict(list)


for i in unq_wrds:
  if i in set(doc1_procd):
    invrtd_index[i].append(0)

  if i in set(doc2_procd):
    invrtd_index[i].append(1)

  if i in set(doc3_procd):
   invrtd_index[i].append(2)

  if i in set(doc4_procd):
    invrtd_index[i].append(3)

  if i in set(doc5_procd):
   invrtd_index[i].append(4)
 

In [18]:
invrtd_index

defaultdict(list,
            {'': [0, 1, 2, 3, 4],
             'smaller': [1],
             'generals': [3],
             'unanimity': [4],
             'workmen': [1],
             'autumn': [0, 4],
             'distracted': [2],
             'north': [0, 1, 3],
             'mend': [4],
             'transitional': [4],
             'accomplish': [1],
             'childs': [4],
             'palette': [1],
             'loved': [0, 1, 4],
             'watermelon': [0],
             'prevented': [1],
             'justified': [1],
             'relinquishes': [3],
             'elm': [0],
             'sweeps': [3],
             'keys': [0],
             'admiration': [0],
             'serious': [1, 4],
             'checked': [4],
             'age': [0, 2, 4],
             'youth': [1, 2, 4],
             'receive': [1, 4],
             'raise': [0],
             'nursed': [1],
             'bird': [0],
             'defiles': [3],
             'ice': [0],
             'superb

In [19]:
#query evaluation function
#helper function 1
def invinx(inp_qry):
  inp_qry=re.sub(r'\bor\b','|',inp_qry)
  inp_qry=re.sub(r'\band\b','&',inp_qry)
  inp_qry=re.sub(r'\bnot\b','{0,1,2,3,4}-',inp_qry)
  l1=inp_qry.split()
  for i in range (len(l1)):
    if l1[i].isalpha():
      if invrtd_index[l1[i]]:
        l1[i]=repr(set(invrtd_index[l1[i]]))
      else:
        l1[i]=repr(set([]))
  exp=' '.join(l1)
  return exp

In [20]:
#helper function 2
def inv_match(inv_doc):
  inv_d={1:'doc1',2:'doc2',3:'doc3',4:'doc4',5:'doc5'}
  for i in set(inv_d.keys())&inv_doc:
    print(inv_d[i])


### Testing against different input queries

In [21]:
#input1
inp_qry='home and nation or not inside'
rslt=invinx(inp_qry)
#print(rslt)
inv_doc=eval(rslt)
print(inv_doc)

{1, 2, 3, 4}


In [22]:
inv_match(inv_doc)

doc1
doc2
doc3
doc4


In [23]:
#input2
inp_qry='leave and paintings'
rslt=invinx(inp_qry)
#print(rslt)
inv_doc=eval(rslt)
print(inv_doc)
inv_match(inv_doc)

{2, 4}
doc2
doc4


In [24]:
#input3
inp_qry='position or motive and feeling'
rslt=invinx(inp_qry)
#print(rslt)
inv_doc=eval(rslt)
print(inv_doc)
inv_match(inv_doc)

{1, 2, 3, 4}
doc1
doc2
doc3
doc4


In [25]:
#input4
inp_qry='position and not motive'
rslt=invinx(inp_qry)
inv_doc=eval(rslt)
print(inv_doc)
inv_match(inv_doc)

{1, 2, 3}
doc1
doc2
doc3
